# Generated by Django 4.1 on 2022-08-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
